#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <math.h>
#include <ctype.h>

#include "input.h"

#define INPUT_BUFFER_SIZE 256

/*
 * Discard all remaining characters from the
 * current input line.
 */
static void clearInputBuffer(void)
{
    int character;

    while ((character = getchar()) != '\n' &&
           character != EOF) {
        /* Discard remaining input. */
    }
}

/*
 * Return a safe prompt string.
 *
 * The public input functions accept const char *prompt.
 * Treating a NULL prompt as an empty string prevents
 * undefined behavior in printf().
 */
static const char *getPrompt(const char *prompt)
{
    return (prompt != NULL) ? prompt : "";
}

/*
 * Remove trailing newline and carriage-return
 * characters from a string.
 */
static void removeLineEnding(char *buffer)
{
    size_t length;

    if (buffer == NULL) {
        return;
    }

    length = strlen(buffer);

    while (length > 0 &&
           (buffer[length - 1] == '\n' ||
            buffer[length - 1] == '\r')) {

        buffer[length - 1] = '\0';
        length--;
    }
}

/*
 * Determine whether a string contains at least
 * one non-whitespace character.
 */
static int containsNonWhitespace(const char *buffer)
{
    if (buffer == NULL) {
        return 0;
    }

    while (*buffer != '\0') {
        if (!isspace((unsigned char)*buffer)) {
            return 1;
        }

        buffer++;
    }

    return 0;
}

/*
 * Read a valid integer from the user.
 *
 * The function keeps asking until the user
 * enters a valid integer within the range
 * supported by the int type.
 */
int readInt(const char *prompt)
{
    char buffer[INPUT_BUFFER_SIZE];

    while (1) {
        char *end;
        long value;

        printf("%s", getPrompt(prompt));

        if (fgets(
                buffer,
                sizeof(buffer),
                stdin
            ) == NULL) {

            /*
             * EOF means input is no longer available.
             * Do not loop forever.
             */
            if (feof(stdin)) {
                printf("\nEnd of input.\n");
                return 0;
            }

            printf(
                "\nInput error. Please try again.\n"
            );

            clearerr(stdin);
            continue;
        }

        errno = 0;

        value = strtol(
            buffer,
            &end,
            10
        );

        /*
         * Allow spaces and tabs after
         * the numeric value.
         */
        while (*end == ' ' ||
               *end == '\t' ||
               *end == '\r') {
            end++;
        }

        /*
         * Accept the newline generated by
         * normal terminal input.
         *
         * Reject anything else.
         */
        if (end == buffer ||
            (*end != '\n' &&
             *end != '\0')) {

            printf(
                "Invalid input. "
                "Please enter a whole number.\n"
            );

            continue;
        }

        /*
         * Check integer overflow/underflow.
         */
        if (errno == ERANGE ||
            value < (long)INT_MIN ||
            value > (long)INT_MAX) {

            printf(
                "Number is out of range.\n"
            );

            continue;
        }

        return (int)value;
    }
}

/*
 * Read an integer within a specified
 * inclusive range.
 */
int readIntRange(
    const char *prompt,
    int min,
    int max
)
{
    /*
     * Validate the range supplied by
     * the calling code.
     */
    if (min > max) {
        fprintf(
            stderr,
            "Internal error: invalid integer range.\n"
        );

        return min;
    }

    while (1) {
        int value = readInt(prompt);

        if (value < min ||
            value > max) {

            printf(
                "Please enter a value between "
                "%d and %d.\n",
                min,
                max
            );

            continue;
        }

        return value;
    }
}

/*
 * Read a floating-point number within
 * a specified inclusive range.
 */
float readFloatRange(
    const char *prompt,
    float min,
    float max
)
{
    char buffer[INPUT_BUFFER_SIZE];

    /*
     * Validate the range supplied by
     * the calling code.
     */
    if (!isfinite(min) ||
        !isfinite(max) ||
        min > max) {

        fprintf(
            stderr,
            "Internal error: invalid floating-point range.\n"
        );

        return min;
    }

    while (1) {
        char *end;
        float value;

        printf("%s", getPrompt(prompt));

        if (fgets(
                buffer,
                sizeof(buffer),
                stdin
            ) == NULL) {

            /*
             * EOF means input is no longer available.
             * Do not loop forever.
             */
            if (feof(stdin)) {
                printf("\nEnd of input.\n");
                return min;
            }

            printf(
                "\nInput error. Please try again.\n"
            );

            clearerr(stdin);
            continue;
        }

        errno = 0;

        value = strtof(
            buffer,
            &end
        );

        /*
         * Allow spaces and tabs after
         * the numeric value.
         */
        while (*end == ' ' ||
               *end == '\t' ||
               *end == '\r') {
            end++;
        }

        /*
         * Reject invalid input such as:
         *
         * abc
         * 85abc
         * empty input
         */
        if (end == buffer ||
            (*end != '\n' &&
             *end != '\0')) {

            printf(
                "Invalid input. "
                "Please enter a number.\n"
            );

            continue;
        }

        /*
         * Reject overflow, underflow,
         * NaN and infinity.
         */
        if (errno == ERANGE ||
            !isfinite(value)) {

            printf(
                "Invalid or out-of-range number.\n"
            );

            continue;
        }

        /*
         * Check the application-specific
         * inclusive range.
         */
        if (value < min ||
            value > max) {

            printf(
                "Please enter a value between "
                "%.2f and %.2f.\n",
                min,
                max
            );

            continue;
        }

        return value;
    }
}

/*
 * Read a non-empty string.
 *
 * The supplied size includes space for
 * the terminating null character.
 *
 * Input longer than the supplied buffer
 * is rejected rather than silently truncated.
 */
void readString(
    const char *prompt,
    char *buffer,
    size_t size
)
{
    /*
     * Validate the destination buffer.
     */
    if (buffer == NULL ||
        size < 2) {

        fprintf(
            stderr,
            "Internal error: invalid string buffer.\n"
        );

        return;
    }

    /*
     * fgets() takes an int as its size
     * argument.
     *
     * Validate the size before converting
     * size_t to int so -Wconversion remains
     * clean.
     */
    if (size > (size_t)INT_MAX) {

        fprintf(
            stderr,
            "Internal error: string buffer is too large.\n"
        );

        return;
    }

    /*
     * Safe conversion because size has
     * already been checked against INT_MAX.
     */
    const int inputSize = (int)size;

    while (1) {
        size_t length;

        printf("%s", getPrompt(prompt));

        if (fgets(
                buffer,
                inputSize,
                stdin
            ) == NULL) {

            /*
             * EOF means input is no longer available.
             * Clear the buffer before returning.
             */
            if (feof(stdin)) {
                buffer[0] = '\0';
                printf("\nEnd of input.\n");
                return;
            }

            printf(
                "\nInput error. Please try again.\n"
            );

            clearerr(stdin);
            continue;
        }

        length = strlen(buffer);

        /*
         * If fgets() captured a newline,
         * this is a complete input line.
         */
        if (length > 0 &&
            buffer[length - 1] == '\n') {

            removeLineEnding(buffer);
        }

        /*
         * If there is no newline, the input
         * was longer than the available buffer.
         */
        else {

            /*
             * Check whether the complete line is
             * still waiting in the input stream.
             */
            clearInputBuffer();

            printf(
                "Input is too long. "
                "Maximum length is %zu characters.\n",
                size - 1
            );

            continue;
        }

        /*
         * Reject empty input and input containing
         * only whitespace.
         */
        if (!containsNonWhitespace(buffer)) {

            printf(
                "Input cannot be empty.\n"
            );

            continue;
        }

        return;
    }
}